apiVersion: apps/v1
kind: Deployment
metadata:
  name: demand-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demand-service
  template:
    metadata:
      labels:
        app: demand-service
    spec:
      containers:
      - name: demand-service
        image: dan210902/demand-service:1.0.0
        ports:
        - containerPort: 8001