apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-dashboard
  template:
    metadata:
      labels:
        app: frontend-dashboard
    spec:
      containers:
      - name: frontend-dashboard
        image: dan210902/frontend-dashboard:1.0.4 # Use a new version
        ports:
        - containerPort: 3000
        env:
          - name: NEXT_PUBLIC_API_URL
            value: "http://localhost:8000" # Use localhost
          - name: NEXT_PUBLIC_PRICING_API_URL
            value: "http://localhost:8002" # Use localhost