apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-dashboard
  template:
    metadata:
      labels:
        app: frontend-dashboard
    spec:
      containers:
      - name: frontend-dashboard
        image: dan210902/frontend-dashboard:1.0.0
        ports:
        - containerPort: 3000
        env:
          - name: NEXT_PUBLIC_API_URL
            value: "http://station-service:8000" # Points to the station Kubernetes service
          - name: NEXT_PUBLIC_PRICING_API_URL
            value: "http://pricing-service:8002" # Points to the pricing Kubernetes service