apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1 # The database is stateful, so we only run one copy
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15 # The official PostgreSQL image
        ports:
        - containerPort: 5432 # Expose the standard Postgres port
        env:
          # Define environment variables for the database configuration
          - name: POSTGRES_DB
            value: "evcharging"
          # Securely get the username and password from the Secret we created
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
        volumeMounts:
          # Mount the persistent volume at the location where Postgres stores its data
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        # Link the volumeMount to the PersistentVolumeClaim we created
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc