apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pricing-service
  template:
    metadata:
      labels:
        app: pricing-service
    spec:
      containers:
      - name: pricing-service
        image: dan210902/pricing-service:1.0.0
        ports:
        - containerPort: 8002