apiVersion: apps/v1
kind: Deployment
metadata:
  name: station-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: station-service
  template:
    metadata:
      labels:
        app: station-service
    spec:
      containers:
      - name: station-service
        image: dan210902/station-service:1.0.1
        ports:
        - containerPort: 8000
        env:
          - name: POSTGRES_HOST
            value: "postgres-service"
          - name: POSTGRES_DB
            value: "evcharging"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10