apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  labels:
    app: postgres
data:
  init.sql: |
    -- Create database schema for EV Charging Network
    CREATE DATABASE ev_charging;
    \c ev_charging;
    
    -- Charging stations table
    CREATE TABLE stations (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        location VARCHAR(200) NOT NULL,
        latitude DECIMAL(10,8),
        longitude DECIMAL(11,8),
        total_connectors INTEGER DEFAULT 4,
        available_connectors INTEGER DEFAULT 4,
        power_rating INTEGER DEFAULT 50, -- kW
        status VARCHAR(20) DEFAULT 'active',
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
    );
    
    -- Pricing rules table
    CREATE TABLE pricing_rules (
        id SERIAL PRIMARY KEY,
        station_id INTEGER REFERENCES stations(id),
        base_price DECIMAL(5,3) DEFAULT 0.25, -- per kWh
        peak_multiplier DECIMAL(3,2) DEFAULT 1.5,
        off_peak_multiplier DECIMAL(3,2) DEFAULT 0.8,
        peak_start_hour INTEGER DEFAULT 8,
        peak_end_hour INTEGER DEFAULT 18,
        created_at TIMESTAMP DEFAULT NOW()
    );
    
    -- Demand forecasts table
    CREATE TABLE demand_forecasts (
        id SERIAL PRIMARY KEY,
        station_id INTEGER REFERENCES stations(id),
        forecast_time TIMESTAMP NOT NULL,
        predicted_demand DECIMAL(5,2), -- percentage 0-100
        confidence_score DECIMAL(3,2), -- 0-1
        created_at TIMESTAMP DEFAULT NOW()
    );
    
    -- Sample data for testing
    INSERT INTO stations (name, location, latitude, longitude, total_connectors, available_connectors) VALUES
    ('Downtown Station', '123 Main St, City Center', 59.3293, 18.0686, 8, 6),
    ('Mall Plaza Charger', '456 Shopping Ave', 59.3345, 18.0632, 4, 4),
    ('Airport Hub', 'Terminal 1, Airport Rd', 59.6519, 17.9186, 12, 8),
    ('University Campus', 'Student Center Parking', 59.3498, 18.0728, 6, 5),
    ('Hospital Emergency', '789 Health Blvd', 59.3167, 18.0975, 4, 3);
    
    INSERT INTO pricing_rules (station_id, base_price, peak_multiplier, off_peak_multiplier) VALUES
    (1, 0.28, 1.8, 0.7),
    (2, 0.25, 1.5, 0.8),
    (3, 0.32, 2.0, 0.6),
    (4, 0.22, 1.4, 0.9),
    (5, 0.30, 1.6, 0.8);
    
    -- Create user for application services
    CREATE USER ev_app_user WITH ENCRYPTED PASSWORD 'ev_secure_pass_2024';
    GRANT ALL PRIVILEGES ON DATABASE ev_charging TO ev_app_user;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ev_app_user;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ev_app_user;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: ev_charging
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres_admin_pass
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - exec pg_isready -U postgres -d ev_charging -h 127.0.0.1 -p 5432
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - exec pg_isready -U postgres -d ev_charging -h 127.0.0.1 -p 5432
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-sql
        configMap:
          name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP